apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempapp
  template:
    metadata:
      labels:
        app: tempapp
    spec:
      containers:
      - name: tempapp
        image: tempappacr.azurecr.io/tempapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
