apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynet8api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynet8api
  template:
    metadata:
      labels:
        app: mynet8api
    spec:
      containers:
      - name: mynet8api
        image: mynet8acr.azurecr.io/mynet8api:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
